insert into PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) values (1, 'Produto 001', 'S');
insert into PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) values (2, 'Produto 002', 'S');
insert into PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS) values (3, 'Produto 003', 'S');

insert into PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) values (1, 1, '000001', 'S');
insert into PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) values (1, 2, '000002', 'S');
insert into PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) values (2, 3, '000003', 'S');
insert into PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) values (2, 4, '000004', 'S');
insert into PRODUTO_COSIF (COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS) values (3, 5, '000005', 'S');

insert into MOVIMENTO_MANUAL (DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF, DES_DESCRICAO, DAT_MOVIMENTO, COD_USUARIO, VAL_VALOR) values (7, 2021, 1, 1, 1, 'Movimento 01', CURRENT_TIMESTAMP(), 'TESTE', 1234.50 );
insert into MOVIMENTO_MANUAL (DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF, DES_DESCRICAO, DAT_MOVIMENTO, COD_USUARIO, VAL_VALOR) values (7, 2021, 2, 1, 2, 'Movimento 02', CURRENT_TIMESTAMP(), 'TESTE', 3234.50 );
insert into MOVIMENTO_MANUAL (DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF, DES_DESCRICAO, DAT_MOVIMENTO, COD_USUARIO, VAL_VALOR) values (7, 2021, 3, 2, 3, 'Movimento 03', CURRENT_TIMESTAMP(), 'TESTE', 134.00 );
insert into MOVIMENTO_MANUAL (DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF, DES_DESCRICAO, DAT_MOVIMENTO, COD_USUARIO, VAL_VALOR) values (8, 2021, 1, 2, 3, 'Movimento 04', CURRENT_TIMESTAMP(), 'TESTE', 1434.00 );
